### ISSUE TITLE
fabric.mod.json requiring 1.17.X and preventing launch on 1.18.1

### ISSUE THREAD

**Issue by lizfinite** [rogi27/Homabric#2]
The currently available .jar on CurseForge for 1.18.1 will prompt users with an error about their Minecraft version. 
Editing the .json within the .jar archive allows the mod to be loaded on 1.18.1 without issue.

**Comment by 27rogi** [comment]
GitHub Actions somehow compiled my 1.18 branch using action from 1.17, I reuploaded file on CurseForge, thanks for your help.
