### ISSUE TITLE
[1.18.1] en_us.json Translations aren't working

### ISSUE THREAD

**Issue by lizfinite** [rogi27/Homabric#3]
Command output as well as GUIs currently do not show the translation text, but their base internal references:
![2021-12-23_03 45 49](https://user-images.githubusercontent.com/36245622/147221913-c692eb1c-726e-4fb5-8f58-ae761aad07b1.png)

**Comment by 27rogi** [comment]
Hello.
Are you playing in multiplayer or singleplayer?

**Comment by lizfinite** [comment]
This happened while testing in Singleplayer

**Comment by 27rogi** [comment]
> This happened while testing in Singleplayer

Ok, can produce this bug, honestly don't know how this happends, I will try to find fix for this.

**Comment by 27rogi** [comment]
Should be fixed, Server Translations API act weird sometimes, I added lang files in assets, this should fix the problem in singleplayer.

**Comment by HappiePlant** [comment]
I am using it server side and it also doesn't show translations :/
(Using v2.0.0 on 1.18.2)
