### ISSUE TITLE
[Suggestion] Wait time for /home

### ISSUE THREAD

**Issue by FighterX9** [rogi27/Homabric#7]
I wanted to suggest a Delay for /home similar to other home mods & plugins, where you'd need to stand still for a bit before being teleported to your home.

I've seen that many people on our servers Abuse the instant teleports to get out of fights whenever. So the addition of a wait time (preferably one that could be interrupted when damaged) would be a great help!

Sorry if this has already been suggested or is a bad suggestion in the first place.

**Comment by 27rogi** [comment]
Thanks for giving an idea, I will try to work on it, shouldn't be that hard.
