### ISSUE TITLE
Resets XP when changing dimensions

### ISSUE THREAD

**Issue by AROD2003** [rogi27/Homabric#8]
I set a home near my nether portal and when i type /home home to go to my house in the overworld, it reset my XP to zero. this applies for going from the overworld to the nether as well.

regardless of the order, changing dimensions (at least overworld and nether, havent made it to the end yet) reset my XP levels.

**Comment by 27rogi** [comment]
Seems weird. Could you provide a list of plugins that are used on server?

**Comment by AROD2003** [comment]
i'm not using a server, just singleplayer. here's a list of my mods:

![Screenshot_10](https://user-images.githubusercontent.com/27162930/169871614-1129c9c1-6c18-4c08-a721-e64adc9598de.png)

**Comment by 27rogi** [comment]
Looks like it's a problem with synchronizaiton between client and server. I encountered it in other mods too when I was playing with my friends. Your levels are not gone, any change in exp or rejoin should restore them, as for now I will try to find some fix for this.
